# Generated by Django 3.0.9 on 2020-08-28 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import ntnui.enums
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initializer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yr_link_nor', models.TextField(null=True)),
                ('yr_link_eng', models.TextField(null=True)),
                ('description_nor', models.TextField(null=True)),
                ('description_eng', models.TextField(null=True)),
                ('directions_nor', models.TextField(null=True)),
                ('directions_eng', models.TextField(null=True)),
                ('parking_nor', models.TextField(null=True)),
                ('parking_eng', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Description',
                'verbose_name_plural': 'Descriptions',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=40, null=True)),
                ('longitude', models.CharField(max_length=40, null=True)),
                ('area', models.CharField(max_length=40, null=True)),
                ('difficulty_info_nor', models.TextField(null=True)),
                ('difficulty_info_eng', models.TextField(null=True)),
                ('terrain_nor', models.CharField(max_length=50, null=True)),
                ('terrain_eng', models.CharField(max_length=50, null=True)),
                ('altitude', models.IntegerField(null=True)),
                ('utm', models.CharField(max_length=40, null=True)),
                ('kartblad', models.TextField(null=True)),
                ('map_pdf', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='KoieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('slug', models.SlugField(default=models.CharField(max_length=40, null=True), editable=False)),
                ('price_member', models.IntegerField(default=40)),
                ('price_not_member', models.IntegerField(default=80)),
                ('number_of_beds', models.IntegerField(default=1)),
                ('koie_type', enumchoicefield.fields.EnumChoiceField(default=ntnui.enums.KoieType(2), enum_class=ntnui.enums.KoieType, max_length=5)),
                ('difficulty', enumchoicefield.fields.EnumChoiceField(default=ntnui.enums.DifficultyType(2), enum_class=ntnui.enums.DifficultyType, max_length=5)),
                ('album', models.TextField(null=True)),
                ('booking_window', models.IntegerField(default=14)),
                ('description', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='koie_booking.Description')),
                ('location', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='koie_booking.Location')),
            ],
            options={
                'verbose_name': 'Koie',
                'verbose_name_plural': 'Koier',
            },
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.PositiveIntegerField()),
                ('transaction', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='koie_booking_bookingpayment_related', to='payments.StripeTransaction')),
            ],
            options={
                'verbose_name': 'Booking Payment',
                'verbose_name_plural': 'Booking Payments',
            },
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('guests_member', models.PositiveIntegerField(default=1)),
                ('guests_not_member', models.PositiveIntegerField(default=1)),
                ('key_status', enumchoicefield.fields.EnumChoiceField(default=ntnui.enums.KeyStatus(1), enum_class=ntnui.enums.KeyStatus, max_length=13)),
                ('paid', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True, null=True)),
                ('booking_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='koie_booking.BookingPayment')),
                ('koie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koie_booking.KoieModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
