# Generated by Django 3.0.10 on 2020-10-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koie_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='contact_email',
            field=models.CharField(default='', max_length=40),
        ),
    ]
