# Generated by Django 3.0.10 on 2020-09-30 11:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koie_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40, null=True)),
                ('phone_number', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
            },
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='guests',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': 'to1@example.com', 'isMember': True, 'name': ' ', 'number': ' '}, verbose_name='Guests'),
        ),
    ]
