# Generated by Django 3.0.10 on 2020-09-30 11:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koie_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='guests',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': 'to1@example.com', 'isMember': True, 'name': ' ', 'number': ' '}, verbose_name='Guests'),
        ),
    ]
