# Generated by Django 3.0.10 on 2020-09-30 13:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import koie_booking.models.guest


class Migration(migrations.Migration):

    dependencies = [
        ('koie_booking', '0002_auto_20200930_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='guests',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=koie_booking.models.guest.get_default_guest, verbose_name='Guests'),
        ),
    ]
