# Generated by Django 3.0.10 on 2020-10-14 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('koie_booking', '0002_bookingmodel_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
