# Generated by Django 3.0.10 on 2020-09-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('koie_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoieReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created_at', models.DateField(auto_now=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('firewood', models.IntegerField(choices=[(0, 'Empty'), (1, 'Almost empty'), (2, 'Half empty/full'), (3, 'Almost full'), (4, 'Full')])),
                ('chopped_up_wood', models.IntegerField(choices=[(0, 'Empty'), (1, 'Almost empty'), (2, 'Half empty/full'), (3, 'Almost full'), (4, 'Full')])),
                ('smoke_detector_is_working', models.BooleanField(default=True)),
                ('gas_is_full', models.BooleanField(default=True)),
                ('gas_burner_primus', models.IntegerField(choices=[(0, 'Ok'), (1, 'Not sure'), (2, 'Broken/missing')])),
                ('axe', models.IntegerField(choices=[(0, 'Ok'), (1, 'Not sure'), (2, 'Broken/missing')])),
                ('hammer', models.IntegerField(choices=[(0, 'Ok'), (1, 'Not sure'), (2, 'Broken/missing')])),
                ('saw', models.IntegerField(choices=[(0, 'Ok'), (1, 'Not sure'), (2, 'Broken/missing')])),
                ('saw_blade', models.IntegerField(choices=[(0, 'Ok'), (1, 'Not sure'), (2, 'Broken/missing')])),
                ('saw_bench', models.IntegerField(choices=[(0, 'Ok'), (1, 'Not sure'), (2, 'Broken/missing')])),
                ('spade', models.IntegerField(choices=[(0, 'Ok'), (1, 'Not sure'), (2, 'Broken/missing')])),
                ('kerosene_lamp', models.IntegerField(choices=[(0, 'Ok'), (1, 'Not sure'), (2, 'Broken/missing')])),
                ('detergent', models.IntegerField(choices=[(0, 'Ok'), (1, 'Not sure'), (2, 'Broken/missing')])),
                ('dishware', models.IntegerField(choices=[(0, 'Ok'), (1, 'Not sure'), (2, 'Broken/missing')])),
                ('cookware', models.IntegerField(choices=[(0, 'Ok'), (1, 'Not sure'), (2, 'Broken/missing')])),
                ('cabin_book', models.IntegerField(choices=[(0, 'Ok'), (1, 'Not sure'), (2, 'Broken/missing')])),
                ('candle_holders', models.IntegerField(choices=[(0, 'Ok'), (1, 'Not sure'), (2, 'Broken/missing')])),
                ('fire_blanket', models.IntegerField(choices=[(0, 'Ok'), (1, 'Not sure'), (2, 'Broken/missing')])),
                ('fire_extinguisher', models.IntegerField(choices=[(0, 'Ok'), (1, 'Not sure'), (2, 'Broken/missing')])),
                ('other_faults', models.TextField(blank=True, null=True)),
                ('boat_status', models.IntegerField(choices=[(0, 'No faults'), (1, 'Broken / can not use'), (2, 'Missing paddles'), (3, 'Missing boat'), (4, 'Did not use/do not know')])),
                ('canoe_status', models.IntegerField(choices=[(0, 'No faults'), (1, 'Broken / can not use'), (2, 'Missing paddles'), (3, 'Missing boat'), (4, 'Did not use/do not know')])),
                ('life_jackets_status', models.IntegerField(choices=[(0, 'No faults'), (1, 'Broken / can not use'), (2, 'Missing life jackets or too few'), (3, 'Did not use/ do not know')])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koie_booking.BookingModel')),
            ],
            options={
                'verbose_name': 'Koie Report',
                'verbose_name_plural': 'Koie Reports',
            },
        ),
    ]
