# Generated by Django 3.0.10 on 2020-09-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('koie_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoieReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created_at', models.DateField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('wood', models.IntegerField()),
                ('smoke_detector', models.CharField(max_length=100)),
                ('gas', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koie_booking.BookingModel')),
            ],
        ),
    ]
