import TableHeader from '@/types/admin/TableHeader';

export const reportTableHeaders: Array<TableHeader> = [
  {
    text: 'Tidsmerke',
    align: 'center',
    justify: 'center',
    sortable: true,
    value: 'timestamp',
  },
  {
    text: 'Koie',
    align: 'center',
    justify: 'center',
    sortable: true,
    value: 'slug',
  },
  {
    text: 'Turdato',
    align: 'center',
    justify: 'center',
    sortable: true,
    value: 'tripDate',
  },
  {
    text: 'Gassbestand',
    align: 'center',
    justify: 'center',
    sortable: true,
    value: 'gasIsFull',
  },
  {
    text: 'Vedstokker',
    align: 'center',
    justify: 'center',
    sortable: true,
    value: 'firewood',
  },
  {
    text: 'Opphuggd ved',
    align: 'center',
    justify: 'center',
    sortable: true,
    value: 'choppedUpWood',
  },
  {
    text: 'Båt',
    align: 'center',
    justify: 'center',
    sortable: true,
    value: 'boatStatus',
  },
  {
    text: 'Kano',
    align: 'center',
    justify: 'center',
    sortable: true,
    value: 'canoeStatus',
  },
  {
    text: 'Redningsvest',
    align: 'center',
    justify: 'center',
    sortable: true,
    value: 'lifeJacketsStatus',
  },
  {
    text: 'Røykvarsler',
    align: 'center',
    justify: 'center',
    sortable: true,
    value: 'smokeDetectorIsWorking',
  },
  {
    text: 'Utstyr',
    align: 'center',
    justify: 'center',
    sortable: false,
    value: 'equipment',
    width: '150',
  },
  {
    text: 'Andre utstyrsfeil',
    align: 'center',
    justify: 'center',
    sortable: false,
    value: 'otherFaults',
    width: '150',
  },
  {
    text: 'Tilbakemelding',
    align: 'center',
    justify: 'center',
    sortable: false,
    value: 'feedback',
    width: '150',
  },
];
