import TableHeader from '@/types/admin/TableHeader';

export const reportTableHeaders: Array<TableHeader> = [
  {
    text: 'Tidsmerke',
    align: 'center',
    justify: 'center',
    sortable: true,
    value: 'timestamp',
    width: '7%',
  },
  {
    text: 'Koie',
    align: 'center',
    justify: 'center',
    sortable: true,
    value: 'slug',
    width: '9%',
  },
  {
    text: 'Turdato',
    align: 'center',
    justify: 'center',
    sortable: true,
    value: 'tripDate',
    width: '7%',
  },
  {
    text: 'Gassbestand',
    align: 'center',
    justify: 'center',
    sortable: false,
    value: 'gasIsFull',
    width: '6%',
  },
  {
    text: 'Vedstokker',
    align: 'center',
    justify: 'center',
    sortable: false,
    value: 'firewood',
    width: '7%',
  },
  {
    text: 'Opphuggd ved',
    align: 'center',
    justify: 'center',
    sortable: false,
    value: 'choppedUpWood',
    width: '8%',
  },
  {
    text: 'Båt',
    align: 'center',
    justify: 'center',
    sortable: false,
    value: 'boatStatus',
    width: '9%',
  },
  {
    text: 'Kano',
    align: 'center',
    justify: 'center',
    sortable: false,
    value: 'canoeStatus',
    width: '9%',
  },
  {
    text: 'Redningsvest',
    align: 'center',
    justify: 'center',
    sortable: false,
    value: 'lifeJacketsStatus',
    width: '6%',
  },
  {
    text: 'Røykvarsler',
    align: 'center',
    justify: 'center',
    sortable: false,
    value: 'smokeDetectorIsWorking',
    width: '5%',
  },
  {
    text: 'Utstyr',
    align: 'center',
    justify: 'center',
    sortable: false,
    value: 'equipment',
    width: '150px',
  },
  {
    text: 'Andre utstyrsfeil',
    align: 'center',
    justify: 'center',
    sortable: false,
    value: 'otherFaults',
    width: '9%',
  },
  {
    text: 'Tilbakemelding',
    align: 'center',
    justify: 'center',
    sortable: false,
    value: 'feedback',
    width: '8%',
  },
];
